# Project Luminext - an ultimate block-stacking puzzle game
# Copyright (C) <2024-2026> <unfavorable_enhancer>
# Contact : <random.likes.apes@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

extends SubViewportContainer
##
## Displays currently editing by [PropertyEditor] object
##
class_name SEObjectWindow

const CAMERA_ZOOM_MIN : float = 0.1
const CAMERA_ZOOM_MAX : float = 4.0
const CAMERA_ZOOM_SPEED : float = 0.05

@onready var viewport : SubViewport = $Viewport
@onready var camera : Camera2D = $Viewport/Camera

var currently_displayed_object : Node = null

var _dragging : bool = false
var _last_mouse_pos : Vector2 = Vector2(0,0)
var _is_focused : bool = false


func _input(event: InputEvent) -> void:
	if not visible : return
	if not _is_focused : return
	
	if event is InputEventMouseButton:
		if event.button_index == MOUSE_BUTTON_RIGHT:
			_dragging = event.pressed
			if _dragging : _last_mouse_pos = event.global_position
		if event.button_index == MOUSE_BUTTON_WHEEL_UP:
			camera.zoom.x = clampf(camera.zoom.x + CAMERA_ZOOM_SPEED, CAMERA_ZOOM_MIN, CAMERA_ZOOM_MAX)
			camera.zoom.y = clampf(camera.zoom.y + CAMERA_ZOOM_SPEED, CAMERA_ZOOM_MIN, CAMERA_ZOOM_MAX)
		if event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			camera.zoom.x = clampf(camera.zoom.x - CAMERA_ZOOM_SPEED, CAMERA_ZOOM_MIN, CAMERA_ZOOM_MAX)
			camera.zoom.y = clampf(camera.zoom.y - CAMERA_ZOOM_SPEED, CAMERA_ZOOM_MIN, CAMERA_ZOOM_MAX)
	
	if event is InputEventMouseMotion and _dragging and event.button_mask == MOUSE_BUTTON_RIGHT:
		camera.position -= event.global_position - _last_mouse_pos
		_last_mouse_pos = event.global_position


## Puts generated by [PropertyEditor] object inside viewport 
func display_object(object : Node) -> void:
	if currently_displayed_object : currently_displayed_object.queue_free()
	currently_displayed_object = object
	$Viewport.add_child(currently_displayed_object)
	
	camera.position = Vector2(0,0)
	camera.zoom = Vector2(1.0,1.0)


func _on_mouse_entered() -> void : _is_focused = true
func _on_mouse_exited() -> void : _is_focused = false
